### ISSUE TITLE
Cannot scroll with arrow keys unless I first click on the page body

### ISSUE THREAD

**Issue by autarch** [OpusVL/perldoc.perl.org#16] opened 2019-06-08 21:30 UTC
When I first load any page, hitting the down arrow doesn't cause the page to scroll. If I click somewhere below the header than it starts working.

Using my scroll wheel does work without clicking.

I'm assuming this has to do with the fixed nav header.

**Comment by hakonhagland** [comment] 2019-06-09 13:28
I cannot scroll with arrow keys or the mouse wheel even if I click the page first. I am using Google Chrome. Dragging the scrollbar at the right edge works, but the scroll bar is hidden by the header so it is not easy to realize there is a scroll bar there.

**Comment by eulmatxlm** [comment] 2019-06-10 08:58
Same issue with firefox. Edge works though.
Incidentally, the bar goes under the nav header **and** the "this is a beta release" link.

**Comment by JohnMica** [comment] 2019-06-10 11:29
i can confirm this is a strange issue indeed.

will investigate and hopefully fix is

**Comment by hakonhagland** [comment] 2019-06-18 14:50
RE: *"I cannot scroll with arrow keys or the mouse wheel ..."* I think the problem is related to the [SmoothScroll](https://github.com/gblazex/smoothscroll) chrome extension. If I disable this extension, the page scrolling starts to work again..

**Comment by JohnMica** [comment] 2019-06-19 08:49
fixed in next release
- updating libs to latest versions

**Closed by JohnMica** 2019-06-19 08:49 UTC
Labels: bug

**Comment by autarch** [comment] 2019-06-22 18:37
I'm still having this issue.
